import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';
import '../models/user.dart';
import '../models/meal.dart';
import '../models/grocery_item.dart';

class StorageService {
  static Database? _database;

  static Future<void> init() async {
    _database = await _initDatabase();
  }

  static Future<Database> _initDatabase() async {
    final dbPath = await getDatabasesPath();
    final path = join(dbPath, 'meal_planning.db');

    return await openDatabase(
      path,
      version: 1,
      onCreate: (db, version) async {
        // Users table
        await db.execute('''
          CREATE TABLE users (
            id TEXT PRIMARY KEY,
            username TEXT NOT NULL,
            email TEXT NOT NULL UNIQUE,
            profileImage TEXT
          )
        ''');

        // Meals table
        await db.execute('''
          CREATE TABLE meals (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            userId TEXT NOT NULL,
            mealType TEXT NOT NULL,
            recipeName TEXT NOT NULL,
            ingredients TEXT NOT NULL,
            steps TEXT NOT NULL,
            calories INTEGER,
            date TEXT NOT NULL,
            createdAt TEXT NOT NULL,
            FOREIGN KEY (userId) REFERENCES users (id)
          )
        ''');

        // Grocery items table
        await db.execute('''
          CREATE TABLE grocery_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            userId TEXT NOT NULL,
            name TEXT NOT NULL,
            isChecked INTEGER NOT NULL DEFAULT 0,
            isAutoGenerated INTEGER NOT NULL DEFAULT 0,
            createdAt TEXT NOT NULL,
            FOREIGN KEY (userId) REFERENCES users (id)
          )
        ''');

        // Settings table
        await db.execute('''
          CREATE TABLE settings (
            userId TEXT PRIMARY KEY,
            breakfastTime TEXT,
            lunchTime TEXT,
            dinnerTime TEXT,
            reminderEnabled INTEGER NOT NULL DEFAULT 1,
            FOREIGN KEY (userId) REFERENCES users (id)
          )
        ''');
      },
    );
  }

  static Database get database {
    if (_database == null) {
      throw Exception('Database not initialized');
    }
    return _database!;
  }

  // User operations
  static Future<void> saveUser(User user) async {
    await database.insert(
      'users',
      user.toJson(),
      conflictAlgorithm: ConflictAlgorithm.replace,
    );
  }

  static Future<User?> getUser(String userId) async {
    final result = await database.query(
      'users',
      where: 'id = ?',
      whereArgs: [userId],
    );
    if (result.isEmpty) return null;
    return User.fromJson(result.first);
  }

  static Future<User?> getUserByEmail(String email) async {
    final result = await database.query(
      'users',
      where: 'email = ?',
      whereArgs: [email],
    );
    if (result.isEmpty) return null;
    return User.fromJson(result.first);
  }

  // Meal operations
  static Future<int> insertMeal(Meal meal) async {
    return await database.insert('meals', meal.toJson());
  }

  static Future<List<Meal>> getMealsByDate(String userId, DateTime date) async {
    final dateStr = date.toIso8601String().split('T')[0];
    final result = await database.query(
      'meals',
      where: 'userId = ? AND date LIKE ?',
      whereArgs: [userId, '$dateStr%'],
      orderBy: 'mealType',
    );
    return result.map((json) => Meal.fromJson(json)).toList();
  }

  static Future<List<Meal>> getAllMeals(String userId) async {
    final result = await database.query(
      'meals',
      where: 'userId = ?',
      whereArgs: [userId],
      orderBy: 'date DESC, mealType',
    );
    return result.map((json) => Meal.fromJson(json)).toList();
  }

  static Future<List<Meal>> searchMeals(String userId, String query) async {
    final result = await database.query(
      'meals',
      where: 'userId = ? AND recipeName LIKE ?',
      whereArgs: [userId, '%$query%'],
      orderBy: 'date DESC',
    );
    return result.map((json) => Meal.fromJson(json)).toList();
  }

  static Future<void> updateMeal(Meal meal) async {
    await database.update(
      'meals',
      meal.toJson(),
      where: 'id = ?',
      whereArgs: [meal.id],
    );
  }

  static Future<void> deleteMeal(String mealId) async {
    await database.delete(
      'meals',
      where: 'id = ?',
      whereArgs: [mealId],
    );
  }

  // Grocery operations
  static Future<int> insertGroceryItem(GroceryItem item) async {
    return await database.insert('grocery_items', item.toJson());
  }

  static Future<List<GroceryItem>> getGroceryItems(String userId) async {
    final result = await database.query(
      'grocery_items',
      where: 'userId = ?',
      whereArgs: [userId],
      orderBy: 'isChecked, createdAt DESC',
    );
    return result.map((json) => GroceryItem.fromJson(json)).toList();
  }

  static Future<void> updateGroceryItem(GroceryItem item) async {
    await database.update(
      'grocery_items',
      item.toJson(),
      where: 'id = ?',
      whereArgs: [item.id],
    );
  }

  static Future<void> deleteGroceryItem(String itemId) async {
    await database.delete(
      'grocery_items',
      where: 'id = ?',
      whereArgs: [itemId],
    );
  }

  static Future<void> deleteAllGroceryItems(String userId) async {
    await database.delete(
      'grocery_items',
      where: 'userId = ?',
      whereArgs: [userId],
    );
  }

  // Settings operations
  static Future<void> saveSettings(String userId, Map<String, dynamic> settings) async {
    await database.insert(
      'settings',
      {'userId': userId, ...settings},
      conflictAlgorithm: ConflictAlgorithm.replace,
    );
  }

  static Future<Map<String, dynamic>?> getSettings(String userId) async {
    final result = await database.query(
      'settings',
      where: 'userId = ?',
      whereArgs: [userId],
    );
    if (result.isEmpty) return null;
    return result.first;
  }
}
