import 'package:flutter/foundation.dart';
import '../models/grocery_item.dart';
import '../services/storage_service.dart';

class GroceryProvider with ChangeNotifier {
  List<GroceryItem> _items = [];
  String? _currentUserId;
  bool _isLoading = false;

  List<GroceryItem> get items => _items;
  bool get isLoading => _isLoading;
  String? get currentUserId => _currentUserId;

  void setUserId(String userId) {
    _currentUserId = userId;
  }

  Future<void> loadItems() async {
    if (_currentUserId == null) return;

    _isLoading = true;
    notifyListeners();

    try {
      _items = await StorageService.getGroceryItems(_currentUserId!);
    } catch (e) {
      debugPrint('Error loading grocery items: $e');
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<bool> addItem(GroceryItem item) async {
    if (_currentUserId == null) return false;

    try {
      final itemId = await StorageService.insertGroceryItem(item);
      final newItem = item.copyWith(id: itemId.toString());
      _items.add(newItem);
      notifyListeners();
      return true;
    } catch (e) {
      debugPrint('Error adding grocery item: $e');
      return false;
    }
  }

  Future<bool> updateItem(GroceryItem item) async {
    if (_currentUserId == null || item.id == null) return false;

    try {
      await StorageService.updateGroceryItem(item);
      final index = _items.indexWhere((i) => i.id == item.id);
      if (index != -1) {
        _items[index] = item;
        notifyListeners();
      }
      return true;
    } catch (e) {
      debugPrint('Error updating grocery item: $e');
      return false;
    }
  }

  Future<bool> deleteItem(String itemId) async {
    if (_currentUserId == null) return false;

    try {
      await StorageService.deleteGroceryItem(itemId);
      _items.removeWhere((i) => i.id == itemId);
      notifyListeners();
      return true;
    } catch (e) {
      debugPrint('Error deleting grocery item: $e');
      return false;
    }
  }

  Future<void> toggleItem(String itemId) async {
    final item = _items.firstWhere((i) => i.id == itemId);
    final updatedItem = item.copyWith(isChecked: !item.isChecked);
    await updateItem(updatedItem);
  }

  Future<void> generateFromMeals(List<String> ingredients) async {
    if (_currentUserId == null) return;

    // Remove duplicates and existing items
    final existingNames = _items.map((i) => i.name.toLowerCase()).toSet();
    final uniqueIngredients = ingredients
        .where((ing) => !existingNames.contains(ing.toLowerCase()))
        .toSet()
        .toList();

    for (final ingredient in uniqueIngredients) {
      final item = GroceryItem(
        userId: _currentUserId!,
        name: ingredient.trim(),
        isAutoGenerated: true,
      );
      await addItem(item);
    }
  }

  Future<void> clearCheckedItems() async {
    final checkedItems = _items.where((i) => i.isChecked).toList();
    for (final item in checkedItems) {
      if (item.id != null) {
        await deleteItem(item.id!);
      }
    }
  }
}
