import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../providers/grocery_provider.dart';
import '../../providers/auth_provider.dart';
import '../../models/grocery_item.dart';

class GroceryListScreen extends StatefulWidget {
  const GroceryListScreen({super.key});

  @override
  State<GroceryListScreen> createState() => _GroceryListScreenState();
}

class _GroceryListScreenState extends State<GroceryListScreen> {
  final TextEditingController _itemController = TextEditingController();

  @override
  void dispose() {
    _itemController.dispose();
    super.dispose();
  }

  Future<void> _addItem() async {
    if (_itemController.text.trim().isEmpty) return;

    final groceryProvider =
        Provider.of<GroceryProvider>(context, listen: false);
    final authProvider = Provider.of<AuthProvider>(context, listen: false);

    if (authProvider.currentUser == null) return;

    final item = GroceryItem(
      userId: authProvider.currentUser!.id,
      name: _itemController.text.trim(),
      isAutoGenerated: false,
    );

    final success = await groceryProvider.addItem(item);

    if (mounted) {
      if (success) {
        _itemController.clear();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Item added to grocery list'),
            backgroundColor: Colors.green,
          ),
        );
      }
    }
  }

  Future<void> _showAddItemDialog() async {
    return showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Add Item'),
        content: TextField(
          controller: _itemController,
          autofocus: true,
          decoration: const InputDecoration(
            labelText: 'Item name',
            border: OutlineInputBorder(),
          ),
          onSubmitted: (_) {
            _addItem();
            Navigator.of(context).pop();
          },
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () {
              _addItem();
              Navigator.of(context).pop();
            },
            child: const Text('Add'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Consumer<GroceryProvider>(
        builder: (context, groceryProvider, _) {
          final items = groceryProvider.items;
          final uncheckedItems = items.where((i) => !i.isChecked).toList();
          final checkedItems = items.where((i) => i.isChecked).toList();

          if (items.isEmpty) {
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(
                    Icons.shopping_cart_outlined,
                    size: 64,
                    color: Colors.grey[400],
                  ),
                  const SizedBox(height: 16),
                  Text(
                    'Your grocery list is empty',
                    style: Theme.of(context).textTheme.titleMedium?.copyWith(
                          color: Colors.grey[600],
                        ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'Add items manually or they will be\nauto-generated from your meals',
                    textAlign: TextAlign.center,
                    style: TextStyle(color: Colors.grey[600]),
                  ),
                ],
              ),
            );
          }

          return Column(
            children: [
              if (checkedItems.isNotEmpty)
                Container(
                  padding: const EdgeInsets.all(8.0),
                  color: Colors.green.shade50,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        '${checkedItems.length} item(s) checked',
                        style: TextStyle(color: Colors.green.shade800),
                      ),
                      TextButton(
                        onPressed: () async {
                          await groceryProvider.clearCheckedItems();
                        },
                        child: Text(
                          'Clear checked',
                          style: TextStyle(color: Colors.green.shade800),
                        ),
                      ),
                    ],
                  ),
                ),
              Expanded(
                child: ListView.builder(
                  padding: const EdgeInsets.all(16.0),
                  itemCount: uncheckedItems.length + checkedItems.length,
                  itemBuilder: (context, index) {
                    final item = index < uncheckedItems.length
                        ? uncheckedItems[index]
                        : checkedItems[index - uncheckedItems.length];
                    final isChecked = item.isChecked;

                    return Dismissible(
                      key: Key(item.id ?? ''),
                      direction: DismissDirection.endToStart,
                      background: Container(
                        alignment: Alignment.centerRight,
                        padding: const EdgeInsets.only(right: 20),
                        color: Colors.red,
                        child: const Icon(Icons.delete, color: Colors.white),
                      ),
                      confirmDismiss: (direction) async {
                        return await showDialog<bool>(
                              context: context,
                              builder: (context) => AlertDialog(
                                title: const Text('Delete Item'),
                                content: Text(
                                    'Remove "${item.name}" from grocery list?'),
                                actions: [
                                  TextButton(
                                    onPressed: () =>
                                        Navigator.of(context).pop(false),
                                    child: const Text('Cancel'),
                                  ),
                                  TextButton(
                                    onPressed: () =>
                                        Navigator.of(context).pop(true),
                                    style: TextButton.styleFrom(
                                        foregroundColor: Colors.red),
                                    child: const Text('Delete'),
                                  ),
                                ],
                              ),
                            ) ??
                            false;
                      },
                      onDismissed: (direction) {
                        groceryProvider.deleteItem(item.id!);
                      },
                      child: Card(
                        margin: const EdgeInsets.only(bottom: 8),
                        color: isChecked ? Colors.grey.shade200 : null,
                        child: CheckboxListTile(
                          value: isChecked,
                          onChanged: (value) {
                            groceryProvider.toggleItem(item.id!);
                          },
                          title: Text(
                            item.name,
                            style: TextStyle(
                              decoration: isChecked
                                  ? TextDecoration.lineThrough
                                  : null,
                              color: isChecked ? Colors.grey : null,
                            ),
                          ),
                          subtitle: item.isAutoGenerated
                              ? Text(
                                  'Auto-generated',
                                  style: TextStyle(
                                    fontSize: 12,
                                    color: Colors.blue.shade700,
                                  ),
                                )
                              : null,
                          secondary: item.isAutoGenerated
                              ? const Icon(Icons.auto_awesome, size: 20)
                              : null,
                        ),
                      ),
                    );
                  },
                ),
              ),
            ],
          );
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _showAddItemDialog,
        child: const Icon(Icons.add),
      ),
    );
  }
}
