class GroceryItem {
  final String? id;
  final String userId;
  final String name;
  final bool isChecked;
  final bool isAutoGenerated;
  final DateTime createdAt;

  GroceryItem({
    this.id,
    required this.userId,
    required this.name,
    this.isChecked = false,
    this.isAutoGenerated = false,
    DateTime? createdAt,
  }) : createdAt = createdAt ?? DateTime.now();

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'userId': userId,
      'name': name,
      'isChecked': isChecked ? 1 : 0,
      'isAutoGenerated': isAutoGenerated ? 1 : 0,
      'createdAt': createdAt.toIso8601String(),
    };
  }

  factory GroceryItem.fromJson(Map<String, dynamic> json) {
    return GroceryItem(
      id: json['id']?.toString(),
      userId: json['userId'],
      name: json['name'],
      isChecked: json['isChecked'] == 1,
      isAutoGenerated: json['isAutoGenerated'] == 1,
      createdAt: DateTime.parse(json['createdAt']),
    );
  }

  GroceryItem copyWith({
    String? id,
    String? userId,
    String? name,
    bool? isChecked,
    bool? isAutoGenerated,
    DateTime? createdAt,
  }) {
    return GroceryItem(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      name: name ?? this.name,
      isChecked: isChecked ?? this.isChecked,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
